//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgDataAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrgDataAccess()
        {
            this.TableDataAccesses = new HashSet<TableDataAccess>();
        }
    
        public int OrgDataAccessId { get; set; }
        public string DataAccessCode { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string Archive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDataAccess> TableDataAccesses { get; set; }
    }
}
